version: "3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorial
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./var/lib/mysql
      - ./docker/db/sql:/sql/init.sql
    ports:
      - 3306:3306

  web:
    container_name: django
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
