name: Django CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          docker-compose build web
          docker-compose up -d
          sleep 15s
          docker ps -a
      - name: Execute tests
        run: |
          echo Copy sql file to docker container from host
          docker cp sql/init.sql mysql:home/user
          docker exec -u 1000 mysql home/user/init.sql > /dev/null

          echo execute test
          chmod +x manage.py
          docker exec django python manage.py test
