name: Docker Django CI Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: tutorial
        ports:
          - 3306:3306
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Change chmod to manage.py
        run: |
          chmod +x manage.py
      - name: Build web component
        run: |
          docker-compose build web
      - name: Make migrations
        run: |
          docker-compose run web ./manage.py makemigrations
      - name: Migrate
        run: |
          docker-compose run web ./manage.py migrate
      - name: Do tests
        run: |
          docker-compose run web ./manage.py test
