name: Docker Django CI Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Change chmod to manage.py
        run: |
          chmod +x manage.py
      - name: Build web component
        run: |
          docker-compose build web
      - name: Make migrations
        run: |
          docker-compose run web ./manage.py makemigrations |
          docker-compose run web ./manage.py migrate
      - name: Do tests
        run: |
          docker-compose run web ./manage.py test
