name: Docker Django CI Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Confirm working directory
        run: |
          pwd
          ls -al
      - name: Docker compose up
        run: |
          docker-compose build web
      - name: Do tests
        run: |
          sudo docker-compose run web ./manage.py test
