name: Docker Django CI Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tutorial
          MYSQL_ROOT_PASSWORD: root
          TZ: "Asia/Tokyo"
        volumes:
          - mysql:/volume_mount
          - ./docker/db/sql:/sql/init.sql
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Change chmod to manage.py
        run: |
          chmod +x manage.py
      - name: Build web component
        run: |
          docker-compose build web
          docker-compose up -d
          sleep 10s
          docker ps -a
      - name: Migrate
        run: |
          docker-compose run web ./manage.py makemigrations
          docker-compose run web ./manage.py migrate
      - name: Do tests
        run: |
          docker-compose run web ./manage.py test
